#!/bin/sh
# 
# BEGIN COPYRIGHT BLOCK
# This Program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 2 of the License.
#
# This Program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this Program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA.
#
# Copyright (C) 2005 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK


function processArgs {

    for arg in $1
    do

        if [ $arg == "--version" ]
        then
            echo ""
            echo "Smart Card Manager: Version: $VERSION ."
            echo ""
            exit 0
        fi

        if [ $arg == "--help" ]
        then
            echo ""
            echo "Smart Card Manager: GUI tool to manage smart cards."
            echo "Run by selecting from the system menu or by typing , esc  at the terminal."
            echo ""
            exit 0
        fi

    done
}

processArgs $*


ESC_PATH=$LIBDIR/esc-1.1.2
ESC_BIN=esc.js
ESC_EXEC=gjs

export OPENSC_CONF=$ESC_PATH/opensc.esc.conf
export GI_TYPELIB_PATH=$ESC_PATH/lib/girepository-1.0
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ESC_PATH/lib

cd $ESC_PATH

$ESC_EXEC --include-path  $ESC_PATH ./$ESC_BIN &

exit 0



